version: 2.1
jobs:
  unit_tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build_test:
    jobs:
      - unit_tests